//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingMall.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_InvoiceDetail
    {
        public int InvoiceID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Tbl_Invoice Tbl_Invoice { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
